svtsave/svtsave/urls.py
from django.conf.urls import patterns, include, url

from core.views.sys import EpisodeCallback

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'svtsave.views.home', name='home'),
#    url(r'^', include('core.urls')),

    url(
        regex=r"^episode/callback/$",
        view=EpisodeCallback,
        name="ep_callback",
    ),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)


urlpatterns += patterns('',
                        url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
                        url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', name='logout'),


                        )

svtsave/core/models.py
# -*- coding: utf-8 -*-

import os
#from datetime import datetime, time
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from annoying.functions import get_config
import requests
from itertools import chain

#from django.utils.timezone import utc

from django.utils.timezone import datetime, timedelta, make_aware, utc


from svtplayapi.models import Show, Episode

class Profile(models.Model):
    user = models.OneToOneField(User, blank=True, unique=True)
    shows = models.ManyToManyField(Show, blank=True, null=True)
    unique = models.CharField(max_length=32, db_index=True, default=os.urandom(16).encode('hex'))



    def get_absolute_url(self):
        return '/profile/'

    def get_feed_url(self):
        return reverse('feed_unique', args=(self.unique, ))


class UserDownloadedShows(models.Model):
    user = models.ForeignKey(User)
    episode = models.ForeignKey(Episode)
#    download_date = models.DateTimeField(blank=True, null=True)

    def __unicode__(self):
        return '%s - %s' % (self.episode.title, self.user)

    def is_downloaded(self):
        if self.episode.state == 3:
            return True
        else:
            return False

# class Notificaton

#class Subscription(models.Model):
#    show = models.ForeignKey(Show)
#    user = models.ForeignKey(User)
#
#    def __unicode__(self):
#        return u"%s - %s" % (self.show, self.user)

#    def get_absolute_url(self):
#        return "/people/%i/" % self.id

svtsave/svtplayapi/models.py
# -*- coding: utf-8 -*-

import os
from django.db import models
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.utils.timezone import datetime, utc
from annoying.functions import get_config
import requests


class Show(models.Model):

    def thumbnail_upload_to(self, filename):
        return "shows/%s" % filename

    title = models.CharField(max_length=255, null=True)
    category = models.ForeignKey('Type', null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    thumbnail = models.ImageField(upload_to=thumbnail_upload_to, max_length=255, blank=True, null=True)
    thumbnail_url = models.URLField(null=True, blank=True)

    def __unicode__(self):
        if self.title:
            return self.title
        return '<nada>'


class Episode(models.Model):

    def thumbnail_upload_to(self, filename):
        return "thumbnails/%s" % filename

    VIEWABLE_IN = (
        (1, 'Världen'),
        (2, 'Sverige')
    )

    VIEWABLE_ON_DEVICE = (
        (1, 'Mobile'),
        (2, 'No mobile')
    )

    KIND_OF = (
        (1, 'Episode'),
        (2, 'Clip')
    )

    title = models.CharField(max_length=255, null=True)
    title_slug = models.CharField(max_length=255, null=True, blank=True)
    full_url = models.URLField(max_length=255, null=True, blank=True)
    url = models.URLField(max_length=255)
    show = models.ForeignKey(Show, related_name='episode_set')
    viewable_in = models.IntegerField(choices=VIEWABLE_IN, default=1)
    viewable_on_device = models.IntegerField(choices=VIEWABLE_ON_DEVICE, default=1)
    kind_of = models.IntegerField(choices=KIND_OF, default=1)
    thumbnail_url = models.URLField(null=True, blank=True)
    thumbnail = models.ImageField(upload_to=thumbnail_upload_to, max_length=255, blank=True, null=True)
    http_status = models.IntegerField(blank=True, null=True)
    http_status_checked_date = models.DateTimeField(null=True, blank=True)
    date_created = models.DateTimeField(null=True, blank=True)
    date_broadcasted = models.DateTimeField(null=True, blank=True)
    date_available_until = models.DateTimeField(null=True, blank=True)
    length = models.CharField(max_length=255, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    recommended = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.date_created = datetime.utcnow().replace(tzinfo=utc)
        super(Episode, self).save(*args, **kwargs)

    def update_http_status(self):
        try:
            req = requests.head(self.url)
            if req.status_code == 404:
                self.http_status = 404

        except requests.exceptions.InvalidURL as inst:
            print 'error', inst
            self.http_status = -1

        except requests.exceptions.ConnectionError as inst:
            print 'error', inst

        self.http_status_checked_date = datetime.utcnow().replace(tzinfo=utc)
        self.save()

    def __unicode__(self):
        if self.title is None:
            return '<nada>'
        return self.title


class Type(models.Model):

    def thumbnail_upload_to(self, filename):
        return "types/%s" % filename

    title = models.CharField(max_length=100, blank=True, null=True)
    html_class = models.CharField(max_length=100)
    url = models.URLField(null=True, blank=True)
    thumbnail = models.ImageField(upload_to=thumbnail_upload_to, max_length=255, blank=True, null=True)
    thumbnail_url = models.URLField(null=True, blank=True)

    def __unicode__(self):
        return unicode(self.title)

svtsave/core/forms.py
from django import forms
from models import Profile


class SubscriptionForm(forms.ModelForm):

    class Meta:
        model = Profile
        exclude = (
            'user',
        )

#    def __init__(self, *args, **kwargs):
#        self.request = kwargs.pop('request', None)
#        super(SubscriptionForm, self).__init__(*args, **kwargs)
#
#    def save(self, commit=True):
#        issue = super(SubscriptionForm, self).save(commit=False)
#        issue.user = self.request.user
#        issue.save()

svtsave/core/views/sys.py
# Create your views here.

from django.views import generic
from django.shortcuts import get_object_or_404, redirect, HttpResponse, HttpResponseRedirect
# from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core import serializers


from notifications import notify
from annoying.functions import get_config
import boto

from core.decorators import patch_view_decorator
from core.utils import reverse
from django.views.decorators.cache import cache_page
login_required = patch_view_decorator(login_required)
#cache_page = patch_view_decorator(cache_page)


from core.models import Profile, Episode, Show, UserDownloadedShows
from core.forms import SubscriptionForm

@login_required
class ProfileDetailView(generic.DetailView):
    model = Profile

    def get_object(self, queryset=None):
        return get_object_or_404(Profile, user=self.request.user)

    def get_queryset(self):
        return get_object_or_404(Profile, user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(**kwargs)
        context['show_list'] = Show.objects.filter(profile__user=self.request.user)
        print dir(self.object.user)
        print self.object.user.userdownloadedshows_set.all()
        context['queue_list'] = self.object.user.userdownloadedshows_set.all().order_by('episode__date_downloaded')
        return context
#
#class StuffListView(generic.ListView):
#    model = Profile

class StuffCreateView(generic.CreateView):
    model = Profile
    form_class = SubscriptionForm

    def get_form(self, form_class):
        form = super(StuffCreateView,self).get_form(form_class) #instantiate using parent
        form.request = self.request
#        form.fields['show'].queryset = Subscription.objects.filter(user=self.request.user)
#        print form.fields
        return form

@login_required
class ProfileUpdateView(generic.UpdateView):
    model = Profile
    form_class = SubscriptionForm

    def get_object(self, queryset=None):
        return get_object_or_404(Profile, user=self.request.user)

@login_required
class EpisodeListView(generic.ListView):
    model = Episode

@login_required
class EpisodeDetailView(generic.DetailView):
    model = Episode

    def get_context_data(self, **kwargs):
        context = super(EpisodeDetailView, self).get_context_data(**kwargs)
        self.object.users_to_notify()
        return context





#@class_view_decorator(login_required)
@login_required
class ShowListView(generic.ListView):
    model = Show
    queryset = Show.objects.all().order_by('title')

@login_required
class ShowDetailView(generic.DetailView):
    model = Show

    def get_context_data(self, **kwargs):
        context = super(ShowDetailView, self).get_context_data(**kwargs)
        context['episode_list'] = Episode.objects.filter(show=self.get_object())
        return context

@login_required
class EpisodePrequeue(generic.RedirectView):

    def get_redirect_url(self, pk):
        ep = get_object_or_404(Episode, pk=pk)
        ep.state = 4
        ep.save()

        queued = UserDownloadedShows.objects.get_or_create(episode=ep, user=self.request.user)

        return self.request.GET.get('next', '/shows/')

@login_required
class EpisodeRequeue(generic.RedirectView):

    def get_redirect_url(self, pk):
        ep = get_object_or_404(Episode, pk=pk)
        ep.state = 4
        ep.save()
        return self.request.GET.get('next', '/shows/')
#
# @login_required
# class EpisodeDownloadView(generic.RedirectView):
#
#     def get_redirect_url(self, pk):
#         print 1
#         ep = get_object_or_404(Episode, pk=pk)
#         if ep.check_if_downloaded_file_exists():
#             print 2
#             return ep.episode_link()
#         else:
#             print 3
#             return reverse('ep_requeue', args=(ep.id, ))


# @login_required()
def EpisodeDownloadView(request, pk):

    from django.utils import simplejson

    print 1
    ep = get_object_or_404(Episode, pk=pk)
    file_exists = ep.check_if_downloaded_file_exists()

    if file_exists:
        # generate_url(expires_in, method='GET', headers=None, force_http=False, response_headers=None, expires_in_absolute=False)
        # get_key(key_name, headers=None, version_id=None, response_headers=None, generation=None, meta_generation=None)
        # url =

        BUCKET = get_config('BUCKET', '')
        GOOGLE_STORAGE = get_config('GOOGLE_STORAGE', '')
        GS_KEY = get_config('GS_KEY', '')
        GS_SECRET = get_config('GS_SECRET', '')

        # uri = boto.storage_uri(BUCKET, GOOGLE_STORAGE)
        # conn = uri.connect(GS_KEY, GS_SECRET)

        from boto.s3.connection import S3Connection
        conn = S3Connection(GS_KEY, GS_SECRET)

        bucket = conn.get_bucket('wlps')

        key = bucket.lookup('%s.mp4' % str(ep.id))
        # key.make_public()

        # dst_uri = boto.storage_uri(
        #     BUCKET + '/' + str(ep.id) + '.mp4', GOOGLE_STORAGE)
        #
        #
        # key = dst_uri.get_key()

        # f = open('torrentfile.torrent', 'w')

        print key
        # print key.get_torrent_file(f)
        #
        # f.close()
        print dir(key)
        # print key.generate_url(3000)
        # print dir(dst_uri)
        # print key.generate_url(4000, response_headers={'content-type': 'application/octet-stream', 'Content-Disposition': 'attachment; filename="fname.ext"' })




    if request.is_ajax:
        if file_exists:
            return HttpResponse(simplejson.dumps({"Exists": 'Yes', 'Link': ep.episode_link()}), content_type="application/json")
        else:
            ep.pre_queue()
            return HttpResponse(simplejson.dumps({"Exists": 'No'}), content_type="application/json")
    else:
        if file_exists:
            print 2
            return HttpResponseRedirect(ep.episode_link())
        else:
            print 3
            # return reverse('ep_requeue', args=(ep.id, ))


@login_required
class StatusView(generic.TemplateView):
    template_name = 'core/status.html'

    def get_context_data(self, **kwargs):
        context = super(StatusView, self).get_context_data(**kwargs)
        context['episodes_prequeued'] = Episode.objects.filter(state=4)
        context['episodes_queued'] = Episode.objects.filter(state=1, http_status=200).exclude(show__profile=None)
        context['episodes_downloading'] = Episode.objects.filter(state=2, http_status=200).exclude(show__profile=None)
        return context



@csrf_exempt
def EpisodeCallback(request):

    req_id = request.POST.get('id')
    if not req_id and settings.DEBUG:
        req_id = request.GET.get('id')

    obj = get_object_or_404(Episode, id=req_id)

    if obj:
        obj.state = 3
        obj.save()

        profiles = obj.users_to_notify()

        for profile in profiles:

            # notify.send(obj, recipient=profile.user, verb='is downloaded', action_object=obj, actions=[serializers.serialize("json", [obj])])
            # notify.send(obj, recipient=profile.user, verb='is downloaded', action_object=obj, href='asd', title='aertert')
            notify.send(obj, recipient=profile.user, verb='is downloaded')

        print profiles

    return HttpResponse('Yay!')


from django.contrib.syndication.views import Feed
from notifications.models import Notification

class LatestEntriesFeed(Feed):
    title = "WLPS Your personal torrent feed"
    link = "http://sys.welovepublicservice.se/"
    # description = ""

    def get_object(self, request, key):
        return get_object_or_404(Profile, unique=key)

    def items(self, obj):
        return Notification.objects.filter(recipient=obj.user, actor_content_type__name='episode')

    def item_title(self, item):
        # return item.actor
        return '%s - %s' % (item.actor.show, item.actor)

    def item_description(self, item):
        return item.description
        # return '%s - %s' % (item.show, item.description)

    def item_link(self, item):
        try:
            return item.actor.episode_link_torrent()
        except:
            pass

svtsave/core/templates/core/episode_detail.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}
{% load url from future %}


{% block content %}
    <p>
        {{ object }} -- {{ object.get_state_display }}
    </p>

    {% if object.state == 0 %}
        <a href="{% url 'ep_queue' object.id %}?next={{ request.get_full_path|urlencode }}">Queue</a>
    {% endif %}

    {% if object.state == 3 %}
        <a href="{{ object.episode_check_link }}">Download</a>
    {% endif %}


{% endblock %}

svtsave/core/templates/core/profile_detail.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}
{% load url from future %}


{% block content %}

    <p>Du prenumerar på följande TV-serier</p>

    <ul>

    {% for item in show_list %}
        <li><a href="{% url 'show_detail' item.id %}">{{ item }}</a></li>
    {% endfor %}

    </ul>


    <p>Följande avsnitt har du köat för inspelning</p>

    <ul>

        {% for item in queue_list %}
            <li class="{% if item.episode.state == 3 %}downloaded{% endif %}"><a href="{% url 'ep_detail' item.episode.id %}">{{ item }}</a></li>
        {% endfor %}

    </ul>


    <p>
    <a href="{% url 'profile_update' %}">Ändra prenumeration</a>
    </p>

{% endblock %}

svtsave/core/templates/core/profile_form.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}
{% load url from future %}

{% block extrahead %}

    {{ block.super }}

    <script src="{{ STATIC_URL }}chosen/chosen/chosen.jquery.min.js" type="text/javascript"></script>

    <link rel="stylesheet" href="{{ STATIC_URL }}chosen/chosen/chosen.css" />


    <script type="text/javascript">

    $(document).ready(function() {
{#        $('#id_show').attr('multiple', true);#}
        $('#id_shows').chosen();
    })

    </script>


{% endblock %}

{% block content %}
<p>
{{ object }}
</p>




<form method="post" action="">
    {% csrf_token %}
        {{ form|as_bootstrap }}

        <div class="actions">
            <button type="submit" class="btn primary">Submit</button>
        </div>
</form>

{% endblock %}

svtsave/core/templates/core/profile_list.html
{{ object_list }}

svtsave/core/templates/core/show_detail.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}
{% load url from future %}


{% block content %}
    <p xmlns="http://www.w3.org/1999/html">
        {{ object }}
    </p>

    <p>Denna TV-serie har följande avsnitt</p>

    <ul>

        {% for item in episode_list %}
            <li><a href="{% url 'ep_detail' item.id %}">{{ item }}</a>

                {% if item.state == 0 %}
                <a href="{% url 'ep_queue' item.id %}?next={{ request.get_full_path|urlencode }}">Queue</a>
                {% endif %}


                {% if item.state == 3 %}
                    <a href="{{ item.episode_check_link }}">Download</a>
                {% endif %}
            </li>
        {% endfor %}

    </ul>

{% endblock %}

svtsave/core/templates/core/show_list.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}
{% load url from future %}
{% load cache %}



{% block content %}

    {% regroup object_list by first_letter as letter_list %}
    <ul>
        {% for letter in letter_list %}
            <li>{{ letter.grouper }}
                <ul class="group">
                    {% for item in letter.list %}
                        <li class="{% if item.has_episodes_downloaded %}downloaded{% endif %}"><a href="{% url 'show_detail' item.id %}">{{ item }}</a></li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>


{% endblock %}

svtsave/core/templates/core/status.html
{% extends 'base.html' %}
{% load bootstrap_toolkit %}
{% load url from future %}


{% block content %}

    <h1>Prequeued</h1>
    <ul>
        {% for item in episodes_prequeued %}
            <li><a href="{% url 'ep_detail' item.id %}">{{ item }}</a></li>
        {% endfor %}
    </ul>

    <h1>Queued</h1>
    <ul>
        {% for item in episodes_queued %}
            <li><a href="{% url 'ep_detail' item.id %}">{{ item }}</a></li>
        {% endfor %}
    </ul>

    <h1>Downloading</h1>
    <ul>
        {% for item in episodes_downloading %}
            <li><a href="{% url 'ep_detail' item.id %}">{{ item }}</a></li>
        {% endfor %}
    </ul>



{% endblock %}